flyway:
    clean-on-validation-error: true
    enabled: true
security.basic.enabled: false
spring:
    datasource:
        driverClassName: org.h2.Driver
        initialize: true
        username: sa
        password: ''
        url: jdbc:h2:file:~/home/vagrant/testdb;AUTO_SERVER=true;DB_CLOSE_DELAY=-1
    h2.console:
            enabled: true
            path: /h2-console
    jpa.hibernate:
        show-sql: true
        ddl-auto: validate
onlineshop.strategy:
    type: PROXIMITY
server:
    context-path: /onlineshop
    spring.jpa.properties.hibernate.type: trace
logging.level:
        org.springframework:
          security: DEBUG




