create table if not exists user_table (user_id bigint not null, user_name VARCHAR not null, password VARCHAR not null, primary key (user_id));
create table if not exists user_roles_table (role_id bigint generated by default as identity, role VARCHAR,fk_user bigint, fk_role bigint, primary key (role_id));

insert into USER_TABLE (user_id, user_name, password) values (1, 'pop', '123');
insert into USER_TABLE (user_id, user_name, password) values (2, 'robb', '456');
insert into USER_TABLE (user_id, user_name, password) values (3, 'dumitru', '123456');

