create table if not exists address_table (address_id bigint generated by default as identity, city varchar(255), country varchar(255), customer_id bigint not null, primary key (address_id));

insert into address_table  (address_id, city, country, customer_id) values (1, 'Timisoara', 'Romania', 1);
insert into address_table  (address_id, city, country, customer_id) values (2, 'Timisoara', 'Romania', 2);
insert into address_table  (address_id, city, country, customer_id) values (3, 'Timisoara', 'Romania', 3);
insert into address_table  (address_id, city, country, customer_id) values (4, 'Brasov', 'Romania', 4);
insert into address_table  (address_id, city, country, customer_id) values (5, 'Sibiu', 'Romania', 5);
insert into address_table  (address_id, city, country, customer_id) values (6, 'Satu Mare', 'Romania', 6);
insert into address_table  (address_id, city, country, customer_id) values (7, 'Baia Mare', 'Romania', 7);
insert into address_table  (address_id, city, country, customer_id) values (8, 'Timisoara', 'Romania', 8);

alter table customer_table add constraint fkAddress foreign key (address_id) references address_table;
