create table if not exists address_table (address_id bigint generated by default as identity, city varchar(255), country varchar(255), customer_id bigint not null, primary key (address_id));

insert into address_table  (address_id, city, country, customer_id) values (1, 'Lampihung', 'Indonesia', 1);
insert into address_table  (address_id, city, country, customer_id) values (2, 'Marinići', 'Croatia', 2);
insert into address_table  (address_id, city, country, customer_id) values (3, 'Shebekino', 'Russia', 3);
insert into address_table  (address_id, city, country, customer_id) values (4, 'Suva Reka', 'Kosovo', 4);
insert into address_table  (address_id, city, country, customer_id) values (5, 'Bachaquero', 'Venezuela', 5);
insert into address_table  (address_id, city, country, customer_id) values (6, 'Chợ Mới', 'Vietnam', 6);
insert into address_table  (address_id, city, country, customer_id) values (7, 'Parung', 'Indonesia', 7);
insert into address_table  (address_id, city, country, customer_id) values (8, 'Beltinci', 'Slovenia', 8);

alter table customer_table add constraint fkAddress foreign key (address_id) references address_table;
